from enum import Enum


class Modes(Enum):
    IONIAN = "ionico"
    DORIAN = "dorico"
    PHRYGIAN = "frigio"
    LYDIAN = "lidio"
    MIXOLYDIAN = "misolidio"
    AEOLIAN = "eolio"
    LOCRIAN = "locrio"
    HARMONIC_MINOR = "ipoionico sesta minore"
    LOCRIAN_MAJOR_THIRTEEN = "locrio sesta maggiore"
    IONIAN_SHARP_FIVE = "ionico aumentato"
    DORIAN_SHARP_ELEVEN = "dorico #11"
    PHRYGIAN_DOMINANT = "frigio dominante"
    LYDIAN_SHARP_NINE = "lidio #9"
    SUPERLOCRIAN_DIMINISHED = "superlocrio diminuito"
    MELODIC_MINOR = "ipoionico"
    DORIAN_FLAT_NINE = "dorico b9"
    LYDIAN_SHARP_FIVE = "lidio aumentato"
    LYDIAN_DOMINANT = "lidio dominante"
    MIXOLYDIAN_FLAT_THIRTEEN = "misolidio b13"
    LOCRIAN_MAJOR_NINE = "locrio nona maggiore"
    SUPERLOCRIAN = "superlocrio"
    DIMINISHED_SEMITONE_TONE = "diminuita semitono tono"
    DIMINISHED_TONE_SEMITONE = "diminuita semitono tono"
    WHOLETONE = "scala esatonale"
