name: Build macOS Universal Binary

on:
  push:
    tags:
      - 'v*'    # Triggers on version tag pushes like v1.0
  workflow_dispatch: # Manual trigger from GitHub UI

jobs:
  build-universal:
    name: Build universal2 binary
    runs-on: macos-latest  # Apple Silicon runner (also works for Intel)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download and install official Python 3.13 universal2
        run: |
          curl -LO https://www.python.org/ftp/python/3.13.4/python-3.13.4-macos11.pkg
          sudo installer -pkg python-3.13.4-macos11.pkg -target /
          
      - name: Check python architecture
        run: file $(which python3)

      - name: Upgrade pip and install PyInstaller
        run: |
          python3 -m pip install --upgrade pip --break-system-packages
          pip install pyinstaller --break-system-packages

      - name: Build universal2 binary with PyInstaller
        run: |
          pyinstaller src/__main__.py --onefile --name caged-trainer --target-architecture universal2

      - name: Upload Universal Binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-universal-binary
          path: dist/caged-trainer
