name: Build macOS and Windows App Bundle with PyInstaller

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-macos-app:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python (universal2)
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"  # 3.11+ from python.org are universal2

      - name: Upgrade pip, setuptools, wheel
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: |
          pip install .
          pip install "pyinstaller>=6.0.0"  # PyInstaller with universal2 support

      - name: Build GUI App Bundle with PyInstaller
        run: |
          pyinstaller \
            --name "CAGED Trainer" \
            --windowed \
            --icon assets/icon.icns \
            --target-architecture universal2 \
            --osx-bundle-identifier com.marchfra.cagedtrainer \
          src/gui.py

      - name: Zip .app for download
        run: |
          ditto \
            -c -k \
            --sequesterRsrc \
            --keepParent \
          dist/CAGED\ Trainer.app caged-trainer-mac.zip

      - name: Upload zipped .app
        uses: actions/upload-artifact@v4
        with:
          name: caged-trainer-mac-app
          path: caged-trainer-mac.zip

  build-windows-app:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Upgrade pip, setuptools, wheel
        run : python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: |
          pip install .
          pip install "pyinstaller>=6.0.0"

      - name: Build GUI App Bundle with PyInstaller
        run: |
          pyinstaller ^
            --name="CAGED Trainer" ^
            --windowed ^
            --icon="assets/icon.ico" ^
            --target-architecture="x86_64" ^
          src/gui.py

      - name: Zip .exe for download
        run: |
          powershell Compress-Archive -Path dist\CAGED\ Trainer.exe -DestinationPath caged-trainer-win.zip

      - name: Upload zipped .exe
        uses: actions/upload-artifact@v4
        with:
          name: caged-trainer-win-app
          path: caged-trainer-win.zip
